Repository adaptlearning/adapt-contrib-accordion, pull requests merged in 2022-07, with the labels that each got.

#117 issue/145 Automated aria levels
  templates/accordion.jsx
Labels: enhancement, accessibility

#119 Missing semantic differentiation between status and heading
  less/accordion.less
  templates/accordion.jsx
Labels: accessibility

#124 Fix: Added gitignore for release automation
  .gitignore
Labels: enhancement
